### ISSUE TITLE
How are the plots in the documentation created?

### ISSUE THREAD

**Issue by Ogaday** [datascopeanalytics/traces#146]
Not a bug, but just curious about how you've plotted the charts in the documentation and what the recommended approach for plotting TimeSeries objects is? I couldn't find a *trace* of this information in the repo. Thanks in advance!

**Comment by stringertheory** [comment]
Good question! Methods for visualization are intentionally excluded (in the spirit of trying to [do one thing well](https://en.wikipedia.org/wiki/Unix_philosophy#Do_One_Thing_and_Do_It_Well)).

It's a bit old school, but the plots in the documentation are created by piping the data into [xmgrace](http://plasma-gate.weizmann.ac.il/Grace/). Say you have a script called `plot.py` that has a TimeSeries you want to visualize (`ts`), you can put:

```python
for t, v in ts:
    print t, v
```

You can do something like `python plot.py | xmgrace -` to redirect the output of the script into xmgrace, adjust the visual formatting as necessary in the GUI, and ultimately output the images as SVG.

**Comment by Ogaday** [comment]
Thanks, that's an interesting approach. I figured out how to do something similar with matplotlib. ([gist](https://gist.github.com/Ogaday/33f1c938eaa65a48e29e5c8f4ffdf197)). Have to set the x axis to display times and also convert the time component to numbers.

**Comment by ricardo-reis-1970** [comment]
Hi @Ogaday,

I literally just landed on traces this week. I have a pandas DataFrame to plot and I too looked at those plots in wonder. I had a column with categorical data that I converted into dummies, so each of them is pretty much like a switch sensor.

Here's my approach:
```
from matplotlib.pyplot import figure
figure(figsize=(16,9))
for i,label in enumerate(['col1', 'col2', 'col3']):
    plt.plot(dummies[label] + i)
```
The idea is, since each series is just `0` or `1`, adding an incrementing `i` to each series will just pile them up If you need more distancing, just multiply `i` by 1.1 in the `plt.plot`, or something.

Now, if anyone knew of a method to load a DataFrame into a `traces` time series...

**Comment by stringertheory** [comment]
@Ogaday @ricardo-reis-1970 I added something in to make quick plots for exploratory analysis https://github.com/datascopeanalytics/traces/blob/dev/examples/Plot.ipynb

And @ricardo-reis-1970 could you give an example of the DataFrame that you'd want to convert into a `traces.TimeSeries`? I think it could be interesting to add that in.

**Comment by ricardo-reis-1970** [comment]
Hi Mike,

I have a set of sensor entries. Here's the head:
```
customerLocationState | startTime | endTime | duration
bedroom | 2018-06-01 23:34:51+02:00 | 2018-06-02 00:24:33+02:00 | 00:49:42
bathroom | 2018-06-02 00:24:33+02:00 | 2018-06-02 00:31:36+02:00 | 00:07:03
bedroom | 2018-06-02 00:31:36+02:00 | 2018-06-02 00:32:26+02:00 | 00:00:50
```
 I replied to the Github notification email with the whole thing. Not sure where that email is going to end up.

In any case, this is your typical Boolean sensor data series, only times 7 or so. Since the values are all mutually exclusive (tracking one person across multiple locations), they've been 'compacted' into one single column `customerLocationState`, but one-hot-encoding them actually recovers the whole individual sensor data.

Your plot on the manual seems to suggest that `traces` can handle multiple series, but all I've seen so far was the ability to merge these into a single one. In my case, I tried the `opeation` parameter but I had some error and I worked around it with Python.

More than the plotting itself, I was looking for a tool to detect patterns and the breaking of these, since this is health monitoring device and routine disruption is usually an emergency. As it seems to me, `traces` is not fully equipped for this **yet**, looking like the focus is more on interpolating and translating into a regular TS.

`traces` looks like a cool thing and a pet project. I like it. If I could help with anything, please let me know. Documentation, perhaps.
